camel:
  component:
    servlet:
      mapping:
        context-path: /services/*
jss:
  camel:
    file:
      enabled: false
      seda:
        enabled: false
      weather:
        enabled: false
      wiretap:
        enabled: false
      hello:
        enabled: false
      rest-dsl:
        enabled: true
